name = "edgeshop"
main = "worker/src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "frontend/dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "edgeshop-db"
database_id = "6290afd0-0301-4220-8212-e920ce046fa3"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "edgeshop-images"

[triggers]
crons = ["0 * * * *"]
