import { HOW_IT_WORKS_STEPS } from './homeContent'

// Real photography for each step (POD-UI2.md §7.2) — replaces the old
// icon-in-circle treatment. Generated by scripts/generate-mockups.py
// (PROCESS_IMAGES) onto the same GROUND / CANVAS footprint as every other
// product mockup, uploaded to local R2 under mockups/ and served through
// the same-origin `/img/*` proxy (worker/src/index.ts) like every other
// catalog image. Explicit width/height keep the section from shifting as
// they load (square source, 1200x1200).
const STEP_IMAGES = [
  { src: '/img/mockups/process-pick-product.webp', alt: 'A plain heather-grey t-shirt with no design, ready to customize' },
  { src: '/img/mockups/process-add-design.webp', alt: 'The same t-shirt now printed with a custom design on the chest' },
  { src: '/img/mockups/process-print-ship.webp', alt: 'A sealed shipping box with the folded, printed t-shirt tucked inside' },
]

function StepImage({ src, alt }: { src: string; alt: string }) {
  return (
    <div className="aspect-square w-full overflow-hidden rounded-card bg-surface-2 ring-1 ring-line">
      <img src={src} alt={alt} width={1200} height={1200} loading="lazy" className="h-full w-full object-cover" />
    </div>
  )
}

/**
 * F5 / §7.2 — "how it works" with real process photography instead of
 * decorative icon circles. Desktop: three steps with images and a
 * connecting line behind the numbered badges (the numbers stay — they're
 * typography, not illustration). Mobile: a tight horizontal snap-scroll
 * carousel instead of a tall vertical stack, so the section stays compact
 * instead of leaving large dead gaps (POD-UI2.md §1 problem #5 / §3/F5).
 *
 * Card width bug note: an earlier pass used `min-w-[78%]` on these
 * carousel cards, but inside a flex row `flex-basis` defaults to `auto`,
 * so `min-width` only ever raised the floor — the card's actual basis was
 * its (much wider) content, which blew a 78%-intended card out to ~604px
 * on a 390px screen. `w-[78%]` sets the basis directly, so the card is
 * actually 78% wide.
 */
export default function HowItWorks() {
  return (
    <section id="how-it-works" className="border-y border-line bg-paper">
      <div className="mx-auto max-w-6xl px-4 py-12 sm:px-8 md:py-20">
        <h2 className="mb-8 text-center font-display text-[1.25rem] font-semibold text-ink md:mb-14 md:text-[1.75rem]">
          How it works
        </h2>

        {/* Mobile / tablet: compact snap-scroll cards. */}
        <div
          className="-mx-4 flex snap-x snap-mandatory gap-4 overflow-x-auto px-4 pb-2 [&::-webkit-scrollbar]:hidden md:hidden"
          style={{ scrollbarWidth: 'none' }}
        >
          {HOW_IT_WORKS_STEPS.map((step, i) => (
            <div
              key={step.title}
              className="stagger-delay animate-fade-up w-[78%] shrink-0 snap-center rounded-card border border-line bg-surface p-4"
              style={{ '--stagger-index': i } as React.CSSProperties}
            >
              <StepImage {...STEP_IMAGES[i]} />
              <div className="mt-3 flex items-center gap-2">
                <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-accent text-[11px] font-bold text-on-accent">
                  {i + 1}
                </span>
                <h3 className="text-sm font-semibold text-ink">{step.title}</h3>
              </div>
              <p className="mt-1.5 text-sm leading-relaxed text-ink-soft">{step.description}</p>
            </div>
          ))}
        </div>

        {/* Desktop: a fixed-height badge row (line + numbers) above each
            image, rather than overlaying the badge on the image itself —
            the image is a responsive aspect-square, so its rendered
            height (and therefore where its bottom edge lands) changes
            with viewport width, which would leave a line anchored to a
            fixed pixel offset out of alignment with it. Anchoring the
            line to the fixed-height badge row instead keeps it exactly
            centred on the badges at every width. */}
        <div className="relative hidden md:grid md:grid-cols-3 md:gap-8">
          <div className="pointer-events-none absolute left-[16.6667%] right-[16.6667%] top-4 h-px bg-line" aria-hidden="true" />
          {HOW_IT_WORKS_STEPS.map((step, i) => (
            <div
              key={step.title}
              className="stagger-delay animate-fade-up relative flex flex-col items-center text-center"
              style={{ '--stagger-index': i } as React.CSSProperties}
            >
              <span className="relative z-10 flex h-8 w-8 items-center justify-center rounded-full bg-accent text-xs font-bold text-on-accent ring-4 ring-paper">
                {i + 1}
              </span>
              <div className="mt-5 w-full">
                <StepImage {...STEP_IMAGES[i]} />
              </div>
              <h3 className="mt-4 text-sm font-semibold text-ink">{step.title}</h3>
              <p className="mt-1.5 max-w-[220px] text-sm leading-relaxed text-ink-soft">{step.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}
